Sprint 6 solution
KatrenkoVladislav/java-kanban pull request #1
Opened 2024-05-09 12:12 UTC by KatrenkoVladislav

Доработка менеджера задач по требованиям ТЗ 6 спринта

2024-05-09 17:56 UTC, YazykovMikhail requested changes

2024-05-09 17:56 UTC, YazykovMikhail commented on src/service/InMemoryHistoryManager.java
> +    Map<Integer, Node<Task>> historyMap = new HashMap<>();
private final
не забывай модификаторы доствпа и что реализация не будет меняться

2024-05-09 17:56 UTC, YazykovMikhail commented on src/service/InMemoryHistoryManager.java
> -        if (task == null){
```
        if (task == null) {
            return;
        }
```
Нужная проверка, стоило оставить

2024-05-09 17:56 UTC, YazykovMikhail commented on src/service/InMemoryHistoryManager.java
> +        historyMap.put(newNode.data.getId(), newNode);
linkLast - занимается настрокайми ссылок, добавлять в историю - это дело метода add
вынеси в add

2024-05-09 17:56 UTC, YazykovMikhail commented on src/service/InMemoryHistoryManager.java
> +    public void remove(int id) {
Вынеси удалени/проверку сюда и тогда не нужно будет еллать лишних и каждый метод будет отвечать за свое:

```
public void remove(int id) {
		final Node node = history.remove(id);
		if (node == null) {
			return;
		}
		removeNode(node);
	}
```

2024-05-09 17:56 UTC, YazykovMikhail commented on src/service/InMemoryHistoryManager.java
> +    Map<Integer, Node<Task>> historyMap = new HashMap<>();
не используй в названиях типы данных и так видно что это Map
просто history

2024-05-09 17:56 UTC, YazykovMikhail commented on src/service/InMemoryHistoryManager.java
>      public void add(Task task) {
В виду всех комментариев будет более структурированней вот так:
```
	public void add(Task task) {
		if (task == null) {
			return;
		}
		final int id = task.getId();
		remove(id);
		linkLast(task);
		history.put(id, tail);
	}
```

2024-05-09 17:56 UTC, YazykovMikhail commented on src/service/InMemoryHistoryManager.java
> +    private void removeNode(Node<Task> node) {
Опусти все приватные методы в низ, сначала идут публичные, а потом уже приватные.
Потому что сначала все смотреят публичные - они точка входа, а потом если нужно разбираются с деталями оеализации

2024-05-09 20:40 UTC, KatrenkoVladislav commented on src/service/InMemoryHistoryManager.java
> +    private void removeNode(Node<Task> node) {
Сделано

2024-05-09 20:40 UTC, KatrenkoVladislav commented on src/service/InMemoryHistoryManager.java
>      public void add(Task task) {
Спасибо за оптимизацию кода) сделано

2024-05-09 20:41 UTC, KatrenkoVladislav commented on src/service/InMemoryHistoryManager.java
> +    public void remove(int id) {
Спасибо за оптимизацию кода) сделано

2024-05-10 06:23 UTC, YazykovMikhail approved these changes

2024-05-10 06:54 UTC, merged