Sprint 7 solution in file manager
KatrenkoVladislav/java-kanban pull request #2
Opened 2024-05-24 21:47 UTC by KatrenkoVladislav

Выполнение ТЗ 7 спринта

2024-05-25 05:52 UTC, YazykovMikhail requested changes

2024-05-25 05:52 UTC, YazykovMikhail commented on resources/task.csv
> +id,type,title,status,description,epic
Молодец что добавил файл в папку resources

2024-05-25 05:52 UTC, YazykovMikhail commented on src/service/Manager.java
>      public static TaskManager getDefault() {
Скорее вот тоа будет выглдяить работа по умолчанию:
	public static TaskManager getDefault() {
		return new FileBackedTaskManager(new File("resources/task.csv"));
	}

2024-05-25 05:52 UTC, YazykovMikhail commented on src/service/FileBackedTaskManager.java
> +            writer.append("id,type,title,status,description,epic");
Вынеси в константу HEADER

2024-05-25 05:52 UTC, YazykovMikhail commented on task.csv
> +id,type,title,status,description,epic
Этот файл лишний, получается

2024-05-25 05:52 UTC, YazykovMikhail commented on test.csv
> +id,type,title,status,description,epic
Этот файл лишний, получается

2024-05-25 05:52 UTC, YazykovMikhail commented on test/service/FileBackedTaskManagerTest.java
> +        manager = new FileBackedTaskManager(Manager.getDefaultHistory(), new File("test.csv"));
можешь сделать папку test/resources и тогда там хранить тестовые файлы

2024-05-25 07:03 UTC, KatrenkoVladislav commented on src/service/FileBackedTaskManager.java
> +            writer.append("id,type,title,status,description,epic");
Не совсем понял, нужно в этом классе создать поле константу private final String HEADER = "id,type,title,status,description,epic"; и потом в методе save() прописать writer.append(HEADER);?

2024-05-25 07:04 UTC, KatrenkoVladislav commented on task.csv
> +id,type,title,status,description,epic
тут тоже не понял, просто в ТЗ есть пример когда в файле первой строкой идет id,type,title,status,description,epic

2024-05-25 07:15 UTC, KatrenkoVladislav commented on test/service/FileBackedTaskManagerTest.java
> +        manager = new FileBackedTaskManager(Manager.getDefaultHistory(), new File("test.csv"));
тут просто две папки создать и тогда нужно прописать тоже путь manager = new FileBackedTaskManager(Manager.getDefaultHistory(), new File("test/resources/test.csv"));?

2024-05-27 17:24 UTC, YazykovMikhail approved these changes

2024-05-28 17:14 UTC, merged